module.exports = {
  rules: {
    'no-new': 0,
    'no-console': 0,
    'no-debugger': 0,
    'spaced-comment': 0,
    'no-unused-expressions': 0,
    'no-param-reassign': 0,
    'no-unused-vars': 1,
    'prefer-destructuring': 0,
    semi: 0,
    'import/extensions': 0,
    'no-plusplus': 0,
    radix: 0,
    'arrow-body-style': 0,
    'class-methods-use-this': 0,
    'func-names': 0,
    camelcase: 0,
    'no-use-before-define': 0,
    'no-var-requires': 0,
    'no-empty-function': 0,
    'space-before-function-paren': 0,
    'prefer-const': 0,
    'linebreak-style': [0, 'error', 'windows'],

    'comma-dangle': [
      'error',
      {
        arrays: 'only-multiline',
        objects: 'only-multiline',
        imports: 'never',
        exports: 'never',
        functions: 'never',
      },
    ],
    'import/no-anonymous-default-export': [
      'error',
      {
        allowArray: true,
        allowArrowFunction: true,
        allowAnonymousClass: true,
        allowAnonymousFunction: true,
        allowCallExpression: true, // The true value here is for backward compatibility
        allowNew: true,
        allowLiteral: true,
        allowObject: true,
      },
    ],
  },
};
